**K-means- Unsupervised Learning**

In [1]:
# K-means  
# k - cluster

# 1. Ask how many clusters (3)
# 2. Take 3 random points on graph
# 3. Calculate distance of data point from random points
# 4. Assign every data point to the random point which is the closest 
# 5. All the points under one random point - will take their centroid and make this as their new random point position
# 6. Once centroid is marked, we will do STEP 3/4/5 again
# 7. Repeat process 6 until max_iter or the points stop moving from one cluster to another

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import seaborn as sns

In [5]:
# 1. How many clusters to take ?
# 2. How to evaluate ?

In [6]:
from sklearn.datasets import load_iris

In [10]:
dataset = load_iris()

In [11]:
df = pd.DataFrame(dataset.data, columns= dataset.feature_names)

In [13]:
df.columns= [col.replace(" (cm)", "").replace(" ", "_") for col in df.columns]

In [15]:
from sklearn.cluster import KMeans

In [16]:
km = KMeans(n_clusters=3) 

In [17]:
km.fit(df)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [19]:
km.cluster_centers_

array([[5.9016129 , 2.7483871 , 4.39354839, 1.43387097],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [6.85      , 3.07368421, 5.74210526, 2.07105263]])

In [20]:
df.sample(1)

sepal_length  sepal_width  petal_length  petal_width
135           7.7          3.0           6.1          2.3

In [21]:
km.predict([[7.7,	3.0,	6.1,	2.3]])

array([2], dtype=int32)

In [22]:
km.inertia_

78.85144142614601

In [23]:
km.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)