In [1]:
pip show numpy

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, torchvision, torchtext, tifffile, thinc, Theano-PyMC, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyerfa, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, nibabel, netCDF4, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lightgbm, librosa, Keras, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-yahoo-finance, fbprophet, f

In [2]:
pip show jump2y

In [3]:
# Install packages

# ! pip install <PACKAGE_NAME>

# Uninstall Package

# ! pip uminstall <PACKAGE_NAME>

# Upgrade package

# ! pip install --upgrade Numpy 

In [4]:
# Install Specific Version
# ! pip install numpy ==1.19.0

## Numpy



In [5]:
list1 = [1,3,5,6,34,2,6,9,78]

In [6]:
list1*2 #multyiplying list with an integer n does not actually perform multiplication function, but repeats the list n number of times

[1, 3, 5, 6, 34, 2, 6, 9, 78, 1, 3, 5, 6, 34, 2, 6, 9, 78]

In [7]:
for item in list1:
  print(item*2)

2
6
10
12
68
4
12
18
156


In [8]:
[i*2 for i in list1]

[2, 6, 10, 12, 68, 4, 12, 18, 156]

In [9]:
# External Library
import numpy as np 
# import the package and name it as np

In [10]:
# Convert list to array
arr1 = np.array(list1)

In [11]:
type(arr1)

numpy.ndarray

In [12]:
arr1

array([ 1,  3,  5,  6, 34,  2,  6,  9, 78])

In [13]:
arr1 *2

array([  2,   6,  10,  12,  68,   4,  12,  18, 156])

In [14]:
arr1 #Didn't save changes yet

array([ 1,  3,  5,  6, 34,  2,  6,  9, 78])

In [15]:
arr1 = arr1 *2 #Now it is howing changes

In [16]:
arr1

array([  2,   6,  10,  12,  68,   4,  12,  18, 156])

In [17]:
arr1.min()

2

In [18]:
arr1.max()

156

In [19]:
arr1.mean()

32.0

In [20]:
arr1.std()

47.74003677324842

In [21]:
arr2 = np.zeros((3,3)) # shape = (rows, column)

In [22]:
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros(shape = (4,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.zeros(shape = (4,3), dtype = int) +5 # Broadcasting

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [25]:
?np.zeros #open help window

In [26]:
np.ones(shape=(3,2)) #rows and columns

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
np.ones(shape=(2,3,2)) #depth, rows and columns

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [28]:
# Random Number Generator

In [29]:
np.random.randint(low = 10, high = 25, size = (3,2)) #randint for random integers

array([[21, 20],
       [24, 10],
       [23, 19]])

In [30]:
np.random.randn(10) #for random float

array([-0.66713696,  0.3394083 , -0.20434981, -1.17389672,  2.21216019,
       -0.46642254,  1.66199507,  0.16768489,  0.97128122, -0.61187372])

In [31]:
# Reshape

In [32]:
arr1= np.random.randn(12)

In [33]:
arr1

array([ 1.25318152,  1.95592483, -0.53685821, -1.46742558, -0.96044199,
       -0.40828522, -0.55144893,  0.14304708, -1.89761283,  2.23154441,
       -0.3824673 ,  1.15330613])

In [34]:
arr1.shape #to know the shape

(12,)

In [39]:
arr1.reshape((6,2)) # To reshape the structure of tablee...all rows, columns and depth. The order for reshape function is depth, rows and columns

array([[ 1.25318152,  1.95592483],
       [-0.53685821, -1.46742558],
       [-0.96044199, -0.40828522],
       [-0.55144893,  0.14304708],
       [-1.89761283,  2.23154441],
       [-0.3824673 ,  1.15330613]])

In [38]:
arr1.reshape((1,4,3))

array([[[ 1.25318152,  1.95592483, -0.53685821],
        [-1.46742558, -0.96044199, -0.40828522],
        [-0.55144893,  0.14304708, -1.89761283],
        [ 2.23154441, -0.3824673 ,  1.15330613]]])

In [40]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
arr4= np.random.randint(low = 0, high= 10, size=20)

In [43]:
arr4

array([5, 8, 9, 3, 9, 2, 6, 0, 3, 2, 8, 9, 0, 9, 7, 4, 1, 2, 8, 3])

In [45]:
arr4.argmax() # To find out the position of maximum number

2

In [63]:
# Golden Rule of PYTHON

# 1. Every mumber starts with ZERO
# 2. In range specified  (m,n) n is exclusive and it will represneted as (m, n-1)

In [47]:
arr4.argmin()

7

In [50]:
arr5= np.random.randint(10,50,(5,3))

In [51]:
arr5

array([[42, 43, 46],
       [32, 42, 15],
       [35, 28, 43],
       [21, 47, 44],
       [30, 46, 16]])

In [53]:
arr5[1,1]  #arr_name[row_number, column_number]

42

In [55]:
arr5[3,1]

47

In [56]:
# Slicing

In [57]:
arr5[2]

array([35, 28, 43])

In [60]:
#To slice a particular part

# arr_name[row_start_number: row_end_number, column_start_number: column_end_number]

In [65]:
arr5[1:3, 0:2]

array([[32, 42],
       [35, 28]])

In [67]:
arr6 = np.random.randint(2,20,10)

In [68]:
arr6

array([12, 12, 19, 14,  7, 14, 15, 13,  5,  9])

In [69]:
np.where(arr6 < 10) #Returns the position of elements

(array([4, 8, 9]),)

In [70]:
np.where(arr6==19)

(array([2]),)

In [71]:
# Problem Statement --> If number is less than 10, multiply it with 2 else leave it as it is

In [72]:
np.where(arr6<10, arr6*2, arr6) # Condition, IF TRUE WHAT TO DO, IF FALSE WHAT TO DO

array([12, 12, 19, 14, 14, 14, 15, 13, 10, 18])